import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { services } from "@/lib/data";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { Check } from "lucide-react";

export default function Home() {
  const heroImage = PlaceHolderImages.find(p => p.id === 'hero-image');

  return (
    <div className="flex flex-col min-h-[100dvh]">
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 relative">
        {heroImage && (
            <Image
              src={heroImage.imageUrl}
              alt={heroImage.description}
              fill
              className="object-cover -z-10"
              priority
              data-ai-hint={heroImage.imageHint}
            />
        )}
        <div className="absolute inset-0 bg-black/50 -z-10" />
        <div className="container px-4 md:px-6 text-white">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="font-headline text-4xl font-bold tracking-tighter sm:text-5xl xl:text-7xl/none">
                  Impeccable Cleaning,
                  <br />
                  Intelligently Planned
                </h1>
                <p className="max-w-[600px] text-gray-200 md:text-xl">
                  CodeSpruce offers premium cleaning services with custom plans generated by AI to perfectly match your needs and budget.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Button asChild size="lg">
                  <Link href="/custom-plan">Generate Your Custom Plan</Link>
                </Button>
                <Button asChild size="lg" variant="secondary">
                  <Link href="#services">Explore Services</Link>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="services" className="w-full py-12 md:py-24 lg:py-32 bg-background">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Our Services</div>
              <h2 className="font-headline text-3xl font-bold tracking-tighter sm:text-5xl">A Fresh Take on Clean</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                From weekly touch-ups to deep-cleaning transformations, we have a service that fits your life.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:gap-12 lg:max-w-none lg:grid-cols-3 pt-12">
            {services.map((service) => {
              const serviceImage = PlaceHolderImages.find(p => p.id === service.image);
              return (
                <Card key={service.id} className="h-full flex flex-col">
                  <CardHeader>
                    {serviceImage && (
                       <Image
                        src={serviceImage.imageUrl}
                        alt={serviceImage.description}
                        width={600}
                        height={400}
                        className="rounded-t-lg object-cover aspect-[3/2]"
                        data-ai-hint={serviceImage.imageHint}
                      />
                    )}
                    <div className="flex items-center gap-4 pt-4">
                       <service.icon className="w-8 h-8 text-primary" />
                       <CardTitle className="font-headline text-2xl">{service.title}</CardTitle>
                    </div>
                    <CardDescription>{service.description}</CardDescription>
                  </CardHeader>
                  <CardContent className="flex flex-col flex-grow">
                    <div className="space-y-4 flex-grow">
                      <h3 className="text-lg font-semibold">What's included:</h3>
                      <ul className="grid gap-2 text-sm text-muted-foreground">
                        {service.tiers[0].features.map((feature) => (
                          <li key={feature} className="flex items-center gap-2">
                            <Check className="w-4 h-4 text-primary" />
                            <span>{feature}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                    <Button asChild className="mt-6 w-full">
                      <Link href="/custom-plan">Get a Quote</Link>
                    </Button>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>
    </div>
  );
}
